obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/



#ifdef CONFIG_VENDOR_REALME
obj-$(CONFIG_OPPO_HYPNUS)     +=  oppo_hypnus/
#endif /* CONFIG_VENDOR_REALME */

